[0]Setup — load Titanic data

In [2]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

# Quick clean (same as Day 5)
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df = df.drop(columns=['Cabin'])

print('Ready! Shape:', df.shape)
print(df.columns.tolist())

Ready! Shape: (891, 11)
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked']

[1]List all unique passenger classes (Pclass). How many are there?
SQL equivalent: SELECT DISTINCT Pclass FROM passengers

In [7]:
print(df['Pclass'].unique())
print(df['Pclass'].nunique())

[3 1 2]
3

[2]Find all female passengers in 1st class who survived. Show Name, Age, Fare.
SQL equivalent: SELECT Name, Age, Fare FROM passengers WHERE Sex='female' AND Pclass=1 AND Survived=1

In [12]:
df[(df['Sex']=='female') & (df['Pclass']==1) & (df['Survived']==1)][['Name','Age','Fare']]

                                                  Name   Age      Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0   71.2833
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0   53.1000
11                            Bonnell, Miss. Elizabeth  58.0   26.5500
31      Spencer, Mrs. William Augustus (Marie Eugenie)  28.0  146.5208
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  49.0   76.7292
..                                                 ...   ...       ...
856         Wick, Mrs. George Dennick (Mary Hitchcock)  45.0  164.8667
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0   25.9292
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0   52.5542
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0   83.1583
887                       Graham, Miss. Margaret Edith  19.0   30.0000

[91 rows x 3 columns]

[3]What is the average fare paid by passengers in each class?
SQL equivalent: SELECT Pclass, AVG(Fare) FROM passengers GROUP BY Pclass

In [20]:
df.groupby('Pclass')['Fare'].mean().round(2)

Pclass
1    84.15
2    20.66
3    13.68
Name: Fare, dtype: float64

[4]Count passengers by embarkation port (Embarked). Sort descending.
SQL equivalent: SELECT Embarked, COUNT(*) as n FROM passengers GROUP BY Embarked ORDER BY n DESC

In [24]:
df.groupby('Embarked').size().sort_values(ascending=False)

Embarked
S    646
C    168
Q     77
dtype: int64

[5]Find passengers with Fare above average. How many are there?
SQL equivalent: SELECT * FROM passengers WHERE Fare > (SELECT AVG(Fare) FROM passengers)

In [35]:
avg = df['Fare'].mean()
print(len(df[df['Fare'] > avg]))

211

[6]Show the top 3 oldest passengers who survived, with their Name and Age.
SQL equivalent: SELECT Name, Age FROM passengers WHERE Survived=1 ORDER BY Age DESC LIMIT 3

In [39]:
df[(df['Survived']==1)][['Name','Age']].sort_values('Age',ascending=False).head(3)

                                     Name   Age
630  Barkworth, Mr. Algernon Henry Wilson  80.0
275     Andrews, Miss. Kornelia Theodosia  63.0
483                Turkula, Mrs. (Hedwig)  63.0

In [40]:
df[(df['Survived']==1)].sort_values('Age',ascending=False)[['Name','Age']].head(3)

                                     Name   Age
630  Barkworth, Mr. Algernon Henry Wilson  80.0
275     Andrews, Miss. Kornelia Theodosia  63.0
483                Turkula, Mrs. (Hedwig)  63.0

[7]Add a column 'FareCategory': Low (<15), Mid (15–50), High (>50).
SQL equivalent: SELECT *, CASE WHEN Fare<15 THEN 'Low' WHEN Fare<=50 THEN 'Mid' ELSE 'High' END AS FareCategory FROM passengers

In [43]:
def fare_cat(f):
    if f < 15: return 'Low'
    elif f <= 50: return 'Mid'
    else: return 'High'
df['FareCategory'] = df['Fare'].apply(fare_cat)
print(df['FareCategory'] )

0       Low
1      High
2       Low
3      High
4       Low
       ...
886     Low
887     Mid
888     Mid
889     Mid
890     Low
Name: FareCategory, Length: 891, dtype: object

[8]What is the survival rate (%) for each FareCategory? (Use the column from Q7)
SQL equivalent: SELECT FareCategory, AVG(Survived) FROM passengers GROUP BY FareCategory

In [44]:
def fare_cat(f):
    if f < 15: return 'Low'
    elif f <= 50: return 'Mid'
    else: return 'High'
df['FareCategory'] = df['Fare'].apply(fare_cat)
df.groupby('FareCategory')['Survived'].mean().round(2)

FareCategory
High    0.68
Low     0.25
Mid     0.43
Name: Survived, dtype: float64

[9]Find all passengers whose name contains 'Mrs' and are younger than 30.
SQL equivalent: SELECT * FROM passengers WHERE Name LIKE '%Mrs%' AND Age < 30

In [53]:
df[(df['Age']>30) & (df['Name'].str.contains('Mrs'))][['Name','Age','Survived']]

                                                  Name   Age  Survived
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0         1
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0         0
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0         1
..                                                 ...   ...       ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0         1
865                           Bystrom, Mrs. (Karolina)  42.0         1
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0         1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0         1
885               Rice, Mrs. William (Margaret Norton)  39.0         0

[70 rows x 3 columns]

[10]Rename columns: 'Survived'→'survived', 'Pclass'→'class', 'Sex'→'gender'. Show first 3 rows.
SQL equivalent: SELECT Survived AS survived, Pclass AS class, Sex AS gender FROM passengers

In [51]:
df.rename(columns={'Survived':'survived','Pclass':'class','Sex':'gender'})[['survived','class','gender']].head(3)

   survived  class  gender
0         0      3    male
1         1      1  female
2         1      3  female